name: Java CI with Maven, SonarQube, and Production Deployment

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Trigger deploy to production'
        required: true
        default: 'false'

jobs:

  build_and_test:
    
    runs-on: [self-hosted, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Build with Maven
        run: mvn clean install -DskipTests
        if: ${{ github.event_name != 'pull_request' }}  # Only run on push events, skip for PR

      - name: Run Unit Tests with Maven
        run: mvn test
        if: ${{ success() }}  # Run this step only if the previous build step succeeded


  upload_artifact:
    runs-on: [self-hosted, staging]
    needs: build_and_test
    if: ${{ needs.build_and_test.result == 'success' }}  # Run only if build and test succeed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Artifact to JFrog Artifactory
        run: |
          echo "Uploading artifact to JFrog Artifactory..."
          curl -u admin:cmVmdGtuOjAxOjE3Njg1OTI4NTc6Y0I3RXloQml0aGV5VlNzMWtCblp1RjVlajNM -T /home/ubuntu/.m2/repository/com/example/my_project/1.0.7/git_actions-1.0.7.war  "http://13.233.110.114:8082/artifactory/git_actions-libs-release//com/efsavage/hello-world-war/"

  # Matrix Job: Deployment to Staging and Production (Self-Hosted EC2 with Tomcat installed)
  deploy:
   
    runs-on: ${{ matrix.environment }}  # Use dynamic environment (staging or production)
    needs: [upload_artifact]  # Waits for SonarQube and Artifactory jobs to complete
    strategy:
      matrix:
        environment: [staging, production]  # Deploy to both staging and production environments
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Tomcat (Staging/Production)
        run: |
          echo "Deploying the script"
          sudo chown -R ubuntu:ubuntu /opt
          cd /opt/apache-tomcat-10.1.34/webapps/
          curl -L -u "admin:cmVmdGtuOjAxOjE3Njg1OTI4NTc6Y0I3RXloQml0aGV5VlNzMWtCblp1RjVlajNM" -O "http://13.233.110.114:8082/artifactory/git_actions-libs-release/com/efsavage/hello-world-war/1.0.7/git_actions-1.0.7.war"
